#!/bin/bash

function get_remote
{
    # if the repo has more than one remote, this is inaccurate
    # I'll fix it if that ever happens to me ¯\_(ツ)_/¯
    echo $(git remote | head -1)
}

function get_default_branch
{
    remote_ref="refs/remotes/$(get_remote)/"
    remote_head=$(git symbolic-ref ${remote_ref}HEAD)
    echo ${remote_head/$remote_ref/}
}
