#!/bin/bash

alias v='nvim'
alias t='tmux'

# DOTNET

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_HTTPREPL_TELEMETRY_OPTOUT=1

alias dn='dotnet'
alias dnr='dotnet run'

# JavaScript

export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]]          && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"

# Misc

source "$HOME/.cargo/env"
