#!/bin/bash

PROMPT_COMMAND=__prepare_prompt

function __prepare_prompt
{
    prev_cmd_exit_code=$?

    if [[ $PWD == $HOME ]]
    then
        dir="~"
    else
        dir=$(basename $PWD)
    fi

    user="${PROMPT_USERNAME:-$BRIGHT_CYAN$(whoami)}$BRIGHT_BLACK: "
    set_win_title="\[\e]2;$dir\a\]"
    dir="$BRIGHT_WHITE$dir"

    git=$(git status 2>/dev/null | awk -f ~/.config/shell/distill_git_status.awk)
    if [[ -n $git ]]
    then
        git="$YELLOW[$git]"
    fi

    if [[ $prev_cmd_exit_code == 0 ]]
    then
        sym="$BRIGHT_WHITE❯"
    else
        sym="$BRIGHT_RED❯"
    fi

    PS1="$set_win_title\n$BOLD$user$dir $git\n$sym $RESET"
}
