#!/bin/bash

PROMPT_COMMAND=__assign_prompt

function __assign_prompt
{
    PS1=$(__prepare_prompt)
}

function __prepare_prompt
(
    prev_cmd_exit_code=$?

    source $HOME/.local/lib/chfont

    if [[ $PWD == $HOME ]]
    then
        dir="~"
    else
        dir=$(basename $PWD)
    fi

    user="${PROMPT_USERNAME:-$(chfont bright-cyan)$(whoami)}$(chfont bright-black):"
    set_win_title="\[\e]2;$dir\a\]"
    dir="$(chfont bright-white)$dir"

    git=$(git status 2>/dev/null | $HOME/.local/lib/shorten-git-status)
    if [[ -n $git ]]
    then
        git="$(chfont yellow)[$git]"
    fi

    if [[ $prev_cmd_exit_code == 0 ]]
    then
        sym_clr="$(chfont bright-white)"
    else
        sym_clr="$(chfont bright-red)"
    fi

    echo "$set_win_title\n$(chfont bold)$user $dir $git\n$sym_clr❯ $(chfont reset)"
)
