#!/bin/bash

# File management:
alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gA='git add -A'
alias gc='git commit'
alias gC='git commit -a'

function cdr {
    root=$(git rev-parse --absolute-git-dir 2>/dev/null | grep -oP '.*(?=/.git)')
    if [[ $? ]]
    then
        cd $root
    else
        echo "Not inside a git repository."
        return 1
    fi
}

# Branch management:
alias gp='git push'
alias gpf='git push --force-with-lease'
alias gsw='git switch'
alias gco='git checkout'
alias gcm='git checkout "$(gitDefaultBranch)"'
alias gf='git fetch -p'
alias gl='git pull'

function glm {
    defaultBranch=$(gitDefaultBranch)
    if [[ $defaultBranch == $(gitCurrentBranch) ]]
    then
        git pull
    else
        git fetch origin "$defaultBranch:$defaultBranch"
    fi
}

function gg {
    num_commits=${1:-10};
    git graph --all -$num_commits
}

function gitCurrentBranch { echo $(git symbolic-ref --short HEAD); }
function gitDefaultBranch { echo "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"; }
