#!/bin/bash

RESET="\[$(tput sgr0)\]"
BOLD="\[$(tput bold)\]"

BLACK="\[$(tput setaf 0)\]"
RED="\[$(tput setaf 1)\]"
GREEN="\[$(tput setaf 2)\]"
YELLOW="\[$(tput setaf 3)\]"
BLUE="\[$(tput setaf 4)\]"
PURPLE="\[$(tput setaf 5)\]"
CYAN="\[$(tput setaf 6)\]"
WHITE="\[$(tput setaf 7)\]"

BRIGHT_BLACK="\[$(tput setaf 8)\]"
BRIGHT_RED="\[$(tput setaf 9)\]"
BRIGHT_GREEN="\[$(tput setaf 10)\]"
BRIGHT_YELLOW="\[$(tput setaf 11)\]"
BRIGHT_BLUE="\[$(tput setaf 12)\]"
BRIGHT_PURPLE="\[$(tput setaf 13)\]"
BRIGHT_CYAN="\[$(tput setaf 14)\]"
BRIGHT_WHITE="\[$(tput setaf 15)\]"

PROMPT_COMMAND=__prepare_prompt

function __prepare_prompt
{
    prev_cmd_exit_code=$?

    if [[ $PWD == $HOME ]]
    then
        dir="~"
    else
        dir=$(basename $PWD)
    fi

    USER="$BRIGHT_CYAN${USERNAMEMAP[$(whoami)]:-$(whoami)}$BRIGHT_BLACK: "
    SET_WIN_TITLE="\[\e]2;$dir\a\]"
    DIR="$BRIGHT_WHITE$dir"

    git=$(git status 2>/dev/null | awk -f ~/.bash/parse_git_status.awk)
    if [[ -n $git ]]
    then
        GIT="$YELLOW[$git]"
    else
        GIT=""
    fi

    if [[ $prev_cmd_exit_code == 0 ]]
    then
        SYM="$BRIGHT_WHITE❯"
    else
        SYM="$BRIGHT_RED❯"
    fi

    PS1="$SET_WIN_TITLE\n$BOLD$USER$DIR $GIT\n$SYM $RESET"
}
