#!/bin/bash

PROMPT_COMMAND=__prepare_prompt

function __prepare_prompt
{
    prev_cmd_exit_code=$?

    if [[ $PWD == $HOME ]]
    then
        dir="~"
    else
        dir=$(basename $PWD)
    fi

    USER="${LOCAL_USERNAME_COLOR:-$BRIGHT_CYAN}${LOCAL_USERNAME:-$(whoami)}$BRIGHT_BLACK: "
    SET_WIN_TITLE="\[\e]2;$dir\a\]"
    DIR="$BRIGHT_WHITE$dir"

    git=$(git status 2>/dev/null | awk -f ~/.bash/parse_git_status.awk)
    if [[ -n $git ]]
    then
        GIT="$YELLOW[$git]"
    else
        GIT=""
    fi

    if [[ $prev_cmd_exit_code == 0 ]]
    then
        SYM="$BRIGHT_WHITE❯"
    else
        SYM="$BRIGHT_RED❯"
    fi

    PS1="$SET_WIN_TITLE\n$BOLD$USER$DIR $GIT\n$SYM $RESET"
}
