#!/bin/bash

#############################
########### Git #############
#############################

alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gA='git add -A'
alias gc='git commit'
alias gC='git commit -a'

function cdr {
    root=$(git rev-parse --absolute-git-dir 2>/dev/null | grep -oP '.*(?=/.git)')
    if [[ $? ]]
    then
        cd $root
    else
        echo "Not inside a git repository."
        return 1
    fi
}

alias gp='git push'
alias gpf='git push --force-with-lease'
alias gsw='git switch'
alias gco='git checkout'
alias gcm='git checkout "$(__default_branch)"'
alias gf='git fetch -p'
alias gl='git pull'

function glm {
    defaultBranch=$(__default_branch)
    if [[ $defaultBranch == $(git branch --show-current) ]]
    then
        git pull
    else
        git fetch origin "$defaultBranch:$defaultBranch"
    fi
}

function gg {
    num_commits=${1:-10};
    git graph --all -$num_commits
}

function __default_branch { echo "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"; }

############################
########## DOTNET ##########
############################

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_HTTPREPL_TELEMETRY_OPTOUT=1

alias dn='dotnet'
alias dnr='dotnet run'

############################
########### MISC ###########
############################

. "$HOME/.cargo/env"

############################
######## JavaScript ########
############################

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

