#!/bin/bash

alias gs='git status'
alias gd='git diff'
alias gds='git diff --staged'
alias ga='git add'
alias gA='git add -A'
alias gc='git commit'
alias gC='git commit -a'

function gsf
{
    git rev-parse 2>/dev/null
    git_exit_code=$?
    if [ $git_exit_code == 0 ]
    then
        git branch -a | grep -vP "\*|HEAD" | sed "s/remotes\/origin\///" | sort | uniq | fzf | xargs -r git switch
    else
        echo "Not a git repository."
        return $git_exit_code
    fi
}


function cdr {
    root=$(git rev-parse --absolute-git-dir 2>/dev/null | grep -oP '.*(?=/.git)')
    if [[ $? ]]
    then
        cd $root
    else
        echo "Not inside a git repository."
        return 1
    fi
}

alias gp='git push'
alias gpf='git push --force-with-lease'
alias gsw='git switch'
alias gsm='git switch "$(__default_branch)"'
alias gf='git fetch -p'
alias gl='git pull'

function glm {
    defaultBranch=$(__default_branch)
    if [[ $defaultBranch == $(git branch --show-current) ]]
    then
        git pull
    else
        git fetch origin "$defaultBranch:$defaultBranch"
    fi
}

function gg {
    num_commits=${1:-10};
    git graph --all -$num_commits
}

function __default_branch { echo "$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"; }
