#!/bin/bash

function set_win_title {
    if [ $PWD = $HOME ]
    then
        title="~"
    else
        title=$PWD
    fi

    echo -ne "\033]0; $(basename "$title") \007"
}

starship_precmd_user_func="set_win_title"
eval "$(starship init bash)"
